"""
dashboard.py — Dashboard export stage.

Serialises DataFrame to JavaScript sidecar files (dashboard_data.js)
and copies dashboard.html for standalone viewing, per analyst.
"""

from __future__ import annotations

import json
import logging
import math
import shutil
from pathlib import Path
from typing import Union

import pandas as pd

from config.paths import OUTPUT_FOLDER
from utils.columns import _DASHBOARD_COLS
from utils.excel import _ensure_dir
from utils.export_core import _sanitize

logger = logging.getLogger(__name__)


def _write_dashboard(folder: Path, data_df: pd.DataFrame, dashboard_html: Path, label: str = "") -> Path:
    """Write dashboard_data.js + copy dashboard.html to a folder."""
    _ensure_dir(folder)
    dest = folder / "dashboard_data.js"

    cols = [c for c in _DASHBOARD_COLS if c in data_df.columns]
    sub  = data_df[cols].copy()

    # Normalise types so json.dumps never chokes
    for col in sub.columns:
        if sub[col].dtype == bool or str(sub[col].dtype) == "boolean":
            sub[col] = sub[col].fillna(False).astype(bool)
        elif sub[col].dtype == object:
            sub[col] = sub[col].fillna("").astype(str)
        else:
            sub[col] = sub[col].where(sub[col].notna(), None)

    records = sub.to_dict(orient="records")

    # Replace Python float nan/inf with None
    def sanitise(obj):
        if isinstance(obj, float) and (math.isnan(obj) or math.isinf(obj)):
            return None
        if isinstance(obj, dict):
            return {k: sanitise(v) for k, v in obj.items()}
        if isinstance(obj, list):
            return [sanitise(v) for v in obj]
        return obj

    records = sanitise(records)

    from datetime import datetime
    payload = json.dumps(records, ensure_ascii=False, indent=None, separators=(",", ":"))
    dest.write_text(
        f"// Auto-generated by dashboard.py — {datetime.now().isoformat()}\n"
        f"window.PIPELINE_DATA={payload};\n",
        encoding="utf-8",
    )

    # Copy dashboard HTML if available
    html_dest = folder / "dashboard.html"
    if dashboard_html.exists():
        shutil.copy(dashboard_html, html_dest)

    logger.info("Dashboard %s -> %s (%d rows)", label, folder, len(records))
    return dest


def export_dashboard_data(
    df: pd.DataFrame,
    output_folder: Union[str, Path] = OUTPUT_FOLDER,
) -> Path:
    """
    Serialises *df* to a JavaScript sidecar file ``dashboard_data.js`` and
    copies ``dashboard.html`` next to it for standalone viewing.

    Also creates per-Responsavel dashboards so each analyst gets their own
    self-contained folder with dashboard.html + dashboard_data.js.

    Only the columns listed in ``_DASHBOARD_COLS`` are included; missing
    columns are silently skipped.  Boolean / NaN / Path values are normalised
    so the resulting JSON is always valid.

    Returns the path of the main output folder.
    """
    out_folder = Path(output_folder)
    _ensure_dir(out_folder)

    # Source dashboard HTML template
    dashboard_html = Path(__file__).resolve().parent.parent.parent.parent / "templates" / "dashboard.html"

    # ── Full dataset (MTSE folder) ────────────────────────────────────
    mtse_folder = out_folder / "MTSE"
    _write_dashboard(mtse_folder, df, dashboard_html, label="FULL")

    # ── Per-Responsavel dashboards ────────────────────────────────────
    if "Responsavel" in df.columns:
        for resp in sorted(df["Responsavel"].dropna().unique()):
            resp_folder = out_folder / _sanitize(resp)
            resp_df = df[df["Responsavel"] == resp]
            _write_dashboard(resp_folder, resp_df, dashboard_html, label=resp)

    return out_folder
